services:
  - type: web
    name: my-rails-app
    env: ruby
    plan: starter
    buildCommand: |
      bundle config set --local without 'development:test'
      bundle install --path vendor/bundle --clean
      bundle exec rake db:migrate
      bundle exec rake assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0 -p 10000
